// AUTO-GENERATED by scripts/cta-images.mjs — do not edit by hand. Run: npm run cta
export type CtaThumb = { alt: string; w: number; h: number; avif: string; webp: string };
export const CTA_THUMBS = {
  "donate": {
    "alt": "Matt Grant",
    "w": 144,
    "h": 144,
    "avif": "/cta/donate-144.avif",
    "webp": "/cta/donate-144.webp"
  }
} as const satisfies Record<string, CtaThumb>;
export type CtaThumbKey = keyof typeof CTA_THUMBS;
