// 50-post social content calendar — a daily countdown to Election Day (Aug 4 2026).
// Faithful to Matt's published platform; name-free contrast; no fabricated quotes,
// stats, or endorsements. Every public post must carry the "Paid for by" line.

export type Pillar =
  | "Children First"
  | "Term Limits"
  | "Smaller Government"
  | "Lower Taxes"
  | "Bio & Values"
  | "Contrast"
  | "GOTV"
  | "Coalition"
  | "Faith & Community";

export type Channel = "X" | "Facebook" | "Instagram";
export type CTA = "Donate" | "Volunteer" | "Vote" | "Learn more" | "Share";

export type SocialPost = {
  id: string;
  day: number; // days to Election Day
  pillar: Pillar;
  persona: string;
  coalition: string;
  channels: Channel[];
  caption: string;
  hashtags: string[];
  cta: CTA;
  graphic: string;
};

export const ELECTION_ISO = "2026-08-04T00:00:00-05:00";

export const SOCIAL_POSTS: SocialPost[] = [
  { id: "D-50", day: 50, pillar: "Bio & Values", persona: "First-time primary voters", coalition: "Neighborhood captains", channels: ["X", "Facebook", "Instagram"], caption: "I'm Matt Grant — a neighbor, a dad, a problem-solver running for Congress in MO-02. Eagle Scout, three public schools, 25 years as a litigator. I don't just talk — I take action. Let's get to work.", hashtags: ["#MattGrant", "#MO02", "#MattGrantForCongress"], cta: "Learn more", graphic: "Logo card with headshot" },
  { id: "D-49", day: 49, pillar: "Bio & Values", persona: "Parents & families", coalition: "Scouting families", channels: ["Facebook", "Instagram"], caption: "Being an Eagle Scout taught me three things: show up, do the work, leave it better than you found it. That's the standard I'll bring to Washington. No exceptions.", hashtags: ["#MattGrant", "#MO02", "#EagleScout", "#ShowUp"], cta: "Learn more", graphic: "Headshot quote card: 'Show up. Do the work. Leave it better.'" },
  { id: "D-48", day: 48, pillar: "Bio & Values", persona: "Suburban women", coalition: "Parents/PTA", channels: ["X", "Facebook", "Instagram"], caption: "My kids went to public school. Three of them. I've coached, volunteered, and sat in those parent-teacher chairs. I know what families here actually need — because I'm raising one here too.", hashtags: ["#MattGrant", "#MO02", "#FamiliesFirst"], cta: "Learn more", graphic: "Family-at-school photo card" },
  { id: "D-47", day: 47, pillar: "Children First", persona: "Parents & families", coalition: "Legal/justice reform", channels: ["X", "Facebook", "Instagram"], caption: "There's one problem no one else will take on: cleaning up corruption in the family court system. Kids get caught in the middle and nobody answers for it. I will. It's why I'm running.", hashtags: ["#MattGrant", "#MO02", "#ChildrenFirst"], cta: "Learn more", graphic: "Studio: headline 'Children First'" },
  { id: "D-46", day: 46, pillar: "Children First", persona: "Parents & families", coalition: "Legal/justice reform", channels: ["X", "Facebook", "Instagram"], caption: "Meet the CHILD Protection Act — Corruption Hiding Inside Legal Dockets. It ties federal Title IV-D dollars to clean family courts. No clean courts, no check. Simple accountability.", hashtags: ["#MattGrant", "#MO02", "#CHILDProtectionAct", "#ChildrenFirst"], cta: "Learn more", graphic: "Studio: 'The CHILD Protection Act' acronym breakdown" },
  { id: "D-45", day: 45, pillar: "Term Limits", persona: "Fiscal conservatives", coalition: "Taxpayer/term-limit advocates", channels: ["X", "Facebook", "Instagram"], caption: "Term limits for the House and Senate — and yes, that includes my own seat. Public service was never meant to be a career. I'll put it in writing.", hashtags: ["#MattGrant", "#MO02", "#TermLimits"], cta: "Learn more", graphic: "Studio: headline 'Term limits — including my own'" },
  { id: "D-44", day: 44, pillar: "Smaller Government", persona: "Fiscal conservatives", coalition: "Taxpayer/term-limit advocates", channels: ["X", "Facebook", "Instagram"], caption: "A smaller, leaner federal government starts with a hiring freeze and voluntary early retirement. Right-size it before you ask taxpayers for another dime. That's the order it should go.", hashtags: ["#MattGrant", "#MO02", "#SmallerGovernment"], cta: "Learn more", graphic: "Studio: headline 'Right-size Washington'" },
  { id: "D-43", day: 43, pillar: "Lower Taxes", persona: "Small-business owners", coalition: "Chambers of commerce", channels: ["X", "Facebook", "Instagram"], caption: "Want lower taxes? Cut the fraud, waste, and bloated headcount first. You don't get to overspend and then send families the bill. Clean the books, then talk rates.", hashtags: ["#MattGrant", "#MO02", "#LowerTaxes"], cta: "Learn more", graphic: "Studio: headline 'Cut the waste first'" },
  { id: "D-42", day: 42, pillar: "Bio & Values", persona: "Fiscal conservatives", coalition: "Neighborhood captains", channels: ["Facebook", "Instagram"], caption: "The Four Priorities I'm taking to Washington: Children First. Term Limits. Smaller Government. Lower Taxes. Real problems, real plans, real action.", hashtags: ["#MattGrant", "#MO02", "#FourPriorities"], cta: "Learn more", graphic: "Four Priorities infographic" },
  { id: "D-41", day: 41, pillar: "Contrast", persona: "First-time primary voters", coalition: "Neighborhood captains", channels: ["X", "Facebook", "Instagram"], caption: "You shouldn't need a fundraiser invitation to reach your member of Congress. I'm holding open town halls in every county — yes, every one. Pull up a chair.", hashtags: ["#MattGrant", "#MO02", "#ShowUp", "#TownHalls"], cta: "Learn more", graphic: "Studio: 'Open town halls in every county'" },
  { id: "D-40", day: 40, pillar: "Coalition", persona: "Rural/new-map county voters", coalition: "Neighborhood captains", channels: ["X", "Facebook", "Instagram"], caption: "MO-02 is bigger than the suburbs now. Jefferson, Washington, Crawford, Gasconade — I'm coming to your county, in person, no strings. Every voice in this district counts.", hashtags: ["#MattGrant", "#MO02", "#EveryCounty"], cta: "Learn more", graphic: "District map: all counties highlighted" },
  { id: "D-39", day: 39, pillar: "Children First", persona: "Suburban women", coalition: "Parents/PTA", channels: ["X", "Facebook", "Instagram"], caption: "What we keep hearing at the doors: 'No one in Washington is standing up for kids stuck in broken family courts.' Now someone is. That's a promise, not a talking point.", hashtags: ["#MattGrant", "#MO02", "#ChildrenFirst"], cta: "Volunteer", graphic: "Door-knock photo: 'At the doors'" },
  { id: "D-38", day: 38, pillar: "Bio & Values", persona: "Veterans", coalition: "Veterans groups", channels: ["X", "Facebook", "Instagram"], caption: "Service isn't a slogan to me — it's a habit. From Scouting to 25 years standing up for people in court, I've spent my life showing up for others. I'll do the same for you.", hashtags: ["#MattGrant", "#MO02", "#Service"], cta: "Learn more", graphic: "Headshot quote card: 'Service is a habit, not a slogan'" },
  { id: "D-37", day: 37, pillar: "Coalition", persona: "Small-business owners", coalition: "Chambers of commerce", channels: ["X", "Facebook", "Instagram"], caption: "I've spent 25 years winning by building coalitions across the aisle — because that's how you actually solve things. Small-business owners of MO-02: let's talk about what's slowing you down.", hashtags: ["#MattGrant", "#MO02", "#SmallBusiness"], cta: "Learn more", graphic: "Coffee-with-owners photo card" },
  { id: "D-36", day: 36, pillar: "Term Limits", persona: "Seniors", coalition: "Taxpayer/term-limit advocates", channels: ["X", "Facebook", "Instagram"], caption: "After more than a decade, the same names keep cycling through Washington. Term limits break the cycle — and I'm willing to limit myself first. Lead by example.", hashtags: ["#MattGrant", "#MO02", "#TermLimits"], cta: "Learn more", graphic: "Studio: 'After more than a decade…'" },
  { id: "D-35", day: 35, pillar: "Lower Taxes", persona: "Fiscal conservatives", coalition: "Taxpayer/term-limit advocates", channels: ["X", "Facebook", "Instagram"], caption: "Every dollar lost to fraud and waste is a dollar squeezed out of a family budget here at home. Find it. Cut it. Then lower the rates. In that order.", hashtags: ["#MattGrant", "#MO02", "#LowerTaxes"], cta: "Donate", graphic: "Studio: 'Find it. Cut it. Lower the rates.'" },
  { id: "D-34", day: 34, pillar: "Smaller Government", persona: "Fiscal conservatives", coalition: "Taxpayer/term-limit advocates", channels: ["X", "Facebook", "Instagram"], caption: "A hiring freeze plus voluntary early retirement shrinks Washington without slashing anyone's livelihood overnight. Smart, humane, overdue. That's how you do smaller government right.", hashtags: ["#MattGrant", "#MO02", "#SmallerGovernment"], cta: "Learn more", graphic: "Studio: 'Hiring freeze + early retirement'" },
  { id: "D-33", day: 33, pillar: "Faith & Community", persona: "Faith community", coalition: "Faith leaders", channels: ["Facebook", "Instagram"], caption: "Honesty. Service. Looking out for the vulnerable. The values I was raised on are the values I'll carry into office. Grateful to the faith leaders of MO-02 — your work holds this community together.", hashtags: ["#MattGrant", "#MO02", "#Faith", "#Community"], cta: "Learn more", graphic: "Community/church-event photo card" },
  { id: "D-32", day: 32, pillar: "Children First", persona: "Parents & families", coalition: "Legal/justice reform", channels: ["X", "Facebook", "Instagram"], caption: "As a litigator for 25 years, I've seen how the system fails kids when no one's watching. The CHILD Protection Act puts a watchdog on it — federal funds for clean courts only.", hashtags: ["#MattGrant", "#MO02", "#CHILDProtectionAct"], cta: "Learn more", graphic: "Studio: 'Federal funds for clean courts only'" },
  { id: "D-31", day: 31, pillar: "Contrast", persona: "First-time primary voters", coalition: "Neighborhood captains", channels: ["X", "Facebook", "Instagram"], caption: "Career politicians get comfortable. I'm not running to get comfortable — I'm running to fix four real things and then make room for the next person. That's the whole job.", hashtags: ["#MattGrant", "#MO02", "#TermLimits", "#ShowUp"], cta: "Learn more", graphic: "Studio: 'Not here to get comfortable'" },
  { id: "D-30", day: 30, pillar: "GOTV", persona: "First-time primary voters", coalition: "Neighborhood captains", channels: ["X", "Facebook", "Instagram"], caption: "30 days to the primary — August 4. Mark your calendar now and make a plan to vote. Primaries are where it's really decided. Be there.", hashtags: ["#MO02", "#MattGrant", "#Vote", "#August4"], cta: "Vote", graphic: "Countdown card: 30 days" },
  { id: "D-29", day: 29, pillar: "Coalition", persona: "Parents & families", coalition: "Parents/PTA", channels: ["X", "Facebook", "Instagram"], caption: "Parents and PTA leaders of MO-02 — you've been carrying this work alone for too long. I want to be your partner in Washington. Reach out: mattgrantforcongress@gmail.com.", hashtags: ["#MattGrant", "#MO02", "#ChildrenFirst", "#PTA"], cta: "Volunteer", graphic: "Logo card with email + phone" },
  { id: "D-28", day: 28, pillar: "Bio & Values", persona: "Suburban women", coalition: "Neighborhood captains", channels: ["Facebook", "Instagram"], caption: "People ask why a 25-year equity partner would trade the courtroom for the campaign trail. Simple: I'm a dad first. The work that matters most is for our kids and our neighbors.", hashtags: ["#MattGrant", "#MO02", "#DadFirst"], cta: "Learn more", graphic: "Candid family photo card" },
  { id: "D-27", day: 27, pillar: "Term Limits", persona: "Young voters", coalition: "Taxpayer/term-limit advocates", channels: ["X", "Instagram"], caption: "Young voters get this instantly: when the same people hold power forever, nothing changes for you. Term limits open the door. I'll hold it open — starting with my own seat.", hashtags: ["#MO02", "#TermLimits", "#MattGrant", "#ShowUp"], cta: "Volunteer", graphic: "Bold text card: 'Open the door'" },
  { id: "D-26", day: 26, pillar: "Lower Taxes", persona: "Small-business owners", coalition: "Chambers of commerce", channels: ["X", "Facebook", "Instagram"], caption: "Small businesses are the backbone of MO-02 — and they feel every wasted federal dollar. Cut the bloat, lower the burden, let owners reinvest in their people. That's the order.", hashtags: ["#MattGrant", "#MO02", "#LowerTaxes", "#SmallBusiness"], cta: "Donate", graphic: "Main-street storefront photo card" },
  { id: "D-25", day: 25, pillar: "Coalition", persona: "Rural/new-map county voters", coalition: "Neighborhood captains", channels: ["X", "Facebook", "Instagram"], caption: "Washington, Crawford, Gasconade, Jefferson — the new map made you part of MO-02, but you've never been an afterthought to me. Town hall coming to your county. Bring your questions.", hashtags: ["#MattGrant", "#MO02", "#EveryCounty", "#TownHalls"], cta: "Learn more", graphic: "County town-hall schedule card" },
  { id: "D-24", day: 24, pillar: "Children First", persona: "Faith community", coalition: "Faith leaders", channels: ["Facebook", "Instagram"], caption: "Protecting children is where everyone should agree. The CHILD Protection Act isn't left or right — it's right and wrong. I'd be honored to have the faith community standing with us.", hashtags: ["#MattGrant", "#MO02", "#ChildrenFirst", "#Faith"], cta: "Learn more", graphic: "Studio: 'Right and wrong, not left and right'" },
  { id: "D-23", day: 23, pillar: "Smaller Government", persona: "Seniors", coalition: "Taxpayer/term-limit advocates", channels: ["X", "Facebook", "Instagram"], caption: "Seniors built this country and shouldn't be footing the bill for Washington's bloat. Smaller, leaner government means your dollars go to what you were promised — not to overhead.", hashtags: ["#MattGrant", "#MO02", "#SmallerGovernment", "#Seniors"], cta: "Learn more", graphic: "Studio: 'Your dollars, your promises'" },
  { id: "D-22", day: 22, pillar: "Contrast", persona: "Fiscal conservatives", coalition: "Taxpayer/term-limit advocates", channels: ["X", "Facebook", "Instagram"], caption: "I don't take the easy path. Cleaning up the family courts is the one nobody else will touch — because it's hard and there's no fundraiser in it. That's exactly why it needs doing.", hashtags: ["#MattGrant", "#MO02", "#ChildrenFirst", "#ShowUp"], cta: "Learn more", graphic: "Studio: 'The work no one else will do'" },
  { id: "D-21", day: 21, pillar: "GOTV", persona: "First-time primary voters", coalition: "Neighborhood captains", channels: ["X", "Facebook", "Instagram"], caption: "Three weeks out. August 4 is the primary — and in a primary, every single vote carries weight. Check your registration today so there are no surprises. Need help? mattgrantforcongress@gmail.com.", hashtags: ["#MO02", "#Vote", "#MattGrant", "#August4"], cta: "Vote", graphic: "Countdown card: 21 days" },
  { id: "D-20", day: 20, pillar: "Coalition", persona: "Veterans", coalition: "Veterans groups", channels: ["X", "Facebook", "Instagram"], caption: "To the veterans of MO-02: you understand duty, accountability, and finishing the mission. That's the campaign we're running. Stand with us — let's bring that standard to Congress.", hashtags: ["#MattGrant", "#MO02", "#Veterans", "#Service"], cta: "Volunteer", graphic: "Veteran-handshake photo card" },
  { id: "D-19", day: 19, pillar: "Bio & Values", persona: "First-time primary voters", coalition: "Neighborhood captains", channels: ["X", "Facebook", "Instagram"], caption: "Matt does not just talk — he takes action. 25 years of winning hard cases by building coalitions across the aisle. That's not a campaign promise. That's a track record.", hashtags: ["#MattGrant", "#MO02", "#Action"], cta: "Learn more", graphic: "Headshot quote card: 'Action, not talk'" },
  { id: "D-18", day: 18, pillar: "Term Limits", persona: "Fiscal conservatives", coalition: "Taxpayer/term-limit advocates", channels: ["X", "Facebook", "Instagram"], caption: "Here's my pledge in one line: term limits for the House and Senate, my own seat included, no exceptions, no fine print. Hold me to it.", hashtags: ["#MattGrant", "#MO02", "#TermLimits"], cta: "Donate", graphic: "Signed-pledge graphic card" },
  { id: "D-17", day: 17, pillar: "Lower Taxes", persona: "Suburban women", coalition: "Chambers of commerce", channels: ["X", "Facebook", "Instagram"], caption: "Family budgets are stretched thin and Washington keeps reaching for more. My answer: stop the waste before you tax the kitchen table. Relief should start with their bloat, not your paycheck.", hashtags: ["#MattGrant", "#MO02", "#LowerTaxes"], cta: "Learn more", graphic: "Studio: 'Their bloat, not your paycheck'" },
  { id: "D-16", day: 16, pillar: "Children First", persona: "Parents & families", coalition: "Legal/justice reform", channels: ["X", "Facebook", "Instagram"], caption: "Title IV-D sends billions in federal dollars through the family court system every year. My plan: tie that money to clean, accountable courts. Follow the dollars, protect the kids.", hashtags: ["#MattGrant", "#MO02", "#CHILDProtectionAct", "#ChildrenFirst"], cta: "Learn more", graphic: "Studio: 'Follow the dollars. Protect the kids.'" },
  { id: "D-15", day: 15, pillar: "GOTV", persona: "First-time primary voters", coalition: "Neighborhood captains", channels: ["X", "Facebook", "Instagram"], caption: "Two weeks. August 4. Make your plan now: when you'll vote, how you'll get there, who you'll bring. Plans beat intentions every time.", hashtags: ["#MO02", "#Vote", "#ShowUp", "#August4"], cta: "Vote", graphic: "Countdown card: 15 days — make your plan" },
  { id: "D-14", day: 14, pillar: "Coalition", persona: "Young voters", coalition: "Neighborhood captains", channels: ["X", "Instagram"], caption: "Two weeks out and we need you. Knock doors, make calls, or just bring three friends to vote on Aug 4. This is how outsiders win — together. Join us.", hashtags: ["#MO02", "#MattGrant", "#Volunteer", "#ShowUp"], cta: "Volunteer", graphic: "Volunteer-team group photo card" },
  { id: "D-13", day: 13, pillar: "Contrast", persona: "Rural/new-map county voters", coalition: "Neighborhood captains", channels: ["X", "Facebook", "Instagram"], caption: "You shouldn't need a fundraiser invitation to reach your member of Congress. I'll keep holding open town halls in every county — after the election, not just before it.", hashtags: ["#MattGrant", "#MO02", "#TownHalls", "#ShowUp"], cta: "Learn more", graphic: "Studio: 'Town halls — before AND after'" },
  { id: "D-12", day: 12, pillar: "Smaller Government", persona: "Fiscal conservatives", coalition: "Taxpayer/term-limit advocates", channels: ["X", "Facebook", "Instagram"], caption: "Smaller government isn't about cruelty — it's about respect for your money. Freeze the hiring, offer early retirement, stop growing what was already too big. Common sense, finally.", hashtags: ["#MattGrant", "#MO02", "#SmallerGovernment"], cta: "Donate", graphic: "Studio: 'Respect for your money'" },
  { id: "D-11", day: 11, pillar: "Bio & Values", persona: "Parents & families", coalition: "Scouting families", channels: ["Facebook", "Instagram"], caption: "An Eagle Scout, a dad, a neighbor who's lived these values his whole life. I'm asking for your vote on August 4 — not for a career, but to fix four real things and pass the torch.", hashtags: ["#MattGrant", "#MO02", "#EagleScout", "#Vote"], cta: "Vote", graphic: "Family + countdown card: 11 days" },
  { id: "D-10", day: 10, pillar: "GOTV", persona: "First-time primary voters", coalition: "Neighborhood captains", channels: ["X", "Facebook", "Instagram"], caption: "10 days. The final stretch. If you believe Washington needs term limits and our kids need a fighter, now's the moment to show it. Vote August 4 — and bring someone with you.", hashtags: ["#MO02", "#Vote", "#MattGrant", "#August4"], cta: "Vote", graphic: "Countdown card: 10 days" },
  { id: "D-9", day: 9, pillar: "GOTV", persona: "Small-business owners", coalition: "Chambers of commerce", channels: ["X", "Facebook", "Instagram"], caption: "Business owners — your time is tight, so make the plan now. Aug 4, before or after the shop. Lower taxes start with cutting waste, and that starts with your vote.", hashtags: ["#MO02", "#Vote", "#LowerTaxes", "#August4"], cta: "Vote", graphic: "Countdown card: 9 days" },
  { id: "D-8", day: 8, pillar: "GOTV", persona: "Seniors", coalition: "Neighborhood captains", channels: ["Facebook", "Instagram"], caption: "Seniors of MO-02: you never miss an election, and we're counting on you again. August 4. Need a ride or have a question? Call (314) 255-7760. We're here to help.", hashtags: ["#MattGrant", "#MO02", "#Vote", "#Seniors"], cta: "Vote", graphic: "Countdown card: 8 days + phone number" },
  { id: "D-7", day: 7, pillar: "GOTV", persona: "First-time primary voters", coalition: "Neighborhood captains", channels: ["X", "Facebook", "Instagram"], caption: "One week to August 4. Confirm your polling place tonight. A clear plan tonight means a sure vote next Tuesday. Let's finish strong.", hashtags: ["#MO02", "#Vote", "#ShowUp", "#August4"], cta: "Vote", graphic: "Countdown card: 7 days — find your poll" },
  { id: "D-6", day: 6, pillar: "Coalition", persona: "Parents & families", coalition: "Parents/PTA", channels: ["X", "Facebook", "Instagram"], caption: "Six days. Parents — this is the children-first vote you've been waiting for. Text a friend, share this post, and meet us at the polls Aug 4. Our kids are counting on us.", hashtags: ["#MattGrant", "#MO02", "#ChildrenFirst", "#Vote"], cta: "Share", graphic: "Countdown card: 6 days" },
  { id: "D-5", day: 5, pillar: "GOTV", persona: "Young voters", coalition: "Neighborhood captains", channels: ["X", "Instagram"], caption: "5 days. Outsiders only win when we out-show-up. Knock, call, post, or just vote and drag a friend along. Aug 4 — make it loud.", hashtags: ["#MO02", "#ShowUp", "#Vote", "#MattGrant"], cta: "Volunteer", graphic: "Countdown card: 5 days" },
  { id: "D-4", day: 4, pillar: "GOTV", persona: "Fiscal conservatives", coalition: "Taxpayer/term-limit advocates", channels: ["X", "Facebook", "Instagram"], caption: "4 days out. A vote for term limits, smaller government, and lower taxes is a vote on August 4 — not a someday wish. Make your plan and stick to it.", hashtags: ["#MO02", "#TermLimits", "#Vote", "#August4"], cta: "Vote", graphic: "Countdown card: 4 days" },
  { id: "D-3", day: 3, pillar: "GOTV", persona: "Suburban women", coalition: "Neighborhood captains", channels: ["X", "Facebook", "Instagram"], caption: "Three days. What we keep hearing at the doors: people are ready for someone who shows up and means it. Be one of them on August 4. Bring your family.", hashtags: ["#MattGrant", "#MO02", "#Vote", "#ShowUp"], cta: "Vote", graphic: "Countdown card: 3 days" },
  { id: "D-2", day: 2, pillar: "GOTV", persona: "First-time primary voters", coalition: "Neighborhood captains", channels: ["X", "Facebook", "Instagram"], caption: "Tomorrow's the day. Polls open August 4. Know your place, set your alarm, bring your ID and a friend. We've come too far to sit this one out. Let's go, MO-02.", hashtags: ["#MO02", "#Vote", "#August4", "#MattGrant"], cta: "Vote", graphic: "Countdown card: 1 day until polls open" },
  { id: "D-1", day: 1, pillar: "GOTV", persona: "First-time primary voters", coalition: "Neighborhood captains", channels: ["X", "Facebook", "Instagram"], caption: "Election Day. Polls are open — go vote. For our kids, for term limits, for a Congress that shows up. I'm Matt Grant and I'd be honored to have your vote today.", hashtags: ["#MattGrant", "#MO02", "#Vote", "#ShowUp"], cta: "Vote", graphic: "Studio: 'Today's the day — VOTE' with polling hours" },
];

export const PILLARS: Pillar[] = [
  "Children First", "Term Limits", "Smaller Government", "Lower Taxes",
  "Bio & Values", "Contrast", "GOTV", "Coalition", "Faith & Community",
];
