// Generates tiny, web-optimized CTA thumbnails from a few curated master images.
//
//   Masters live in  web/scripts/cta-masters/  (NOT in public/, so the heavy
//   originals are never served). Run:  npm run cta
//
// For each manifest entry this emits an AVIF (primary) + WebP (universal
// fallback) square thumbnail into web/public/cta/, and writes a typed manifest
// (web/lib/cta-manifest.generated.ts) with baked-in dimensions so the <CtaButton>
// renders with width/height set and never causes layout shift.
//
// Safety (mirrors lib/images.ts): metadata is stripped, EXIF orientation baked,
// every derivative is re-encoded smaller than its master, and a hard per-image
// BYTE BUDGET fails the build if any thumbnail comes out too large — so a bad
// master can never silently ship a bloated menu image.

import sharp from "sharp";
import { mkdir, writeFile, stat } from "node:fs/promises";
import path from "node:path";

const ROOT = process.cwd();
const MASTERS = path.join(ROOT, "scripts", "cta-masters");
const OUT = path.join(ROOT, "public", "cta");
const MANIFEST_TS = path.join(ROOT, "lib", "cta-manifest.generated.ts");

const BUDGET_BYTES = 12_000; // hard cap per derivative; build fails if exceeded
const SIZE = 144; // intrinsic px of the square thumbnail (covers retina at ≤72px display)

// Curated CTA masters. `extract` (optional) pre-crops a square region of a
// busy/landscape master — {left, top, size} in source pixels — before the
// downscale, so we keep just the iconic part (a face, the shield). `position`
// is the fallback crop gravity when no extract is given. Add an entry here + a
// derivative is generated; wiring it to a CTA is done in lib/cta-images.ts.
const MANIFEST = [
  {
    key: "donate",
    master: "avatar-circle.png",
    alt: "Matt Grant",
    position: "centre",
  },
  {
    key: "act",
    master: "flyer-service-before-self.png",
    alt: "Take action with Matt Grant",
    extract: { left: 70, top: 150, size: 360 }, // Matt's face + flag
  },
  {
    key: "issues",
    master: "infographic.png",
    alt: "Matt Grant's priorities for Missouri",
    extract: { left: 1250, top: 95, size: 300 }, // the campaign shield
  },
];

const exists = (p) => stat(p).then(() => true).catch(() => false);

async function build() {
  await mkdir(OUT, { recursive: true });
  const entries = {};
  const report = [];

  for (const item of MANIFEST) {
    const src = path.join(MASTERS, item.master);
    if (!(await exists(src))) {
      throw new Error(`[cta] missing master: scripts/cta-masters/${item.master} (run the S3 pull first)`);
    }
    const masterBytes = (await stat(src)).size;

    // Square cover-crop at SIZE, EXIF baked + metadata stripped (sharp drops
    // metadata by default on re-encode). One pipeline reused for both formats.
    const base = () => {
      const p = sharp(src, { failOn: "none" }).rotate();
      if (item.extract) {
        const { left, top, size } = item.extract;
        p.extract({ left, top, width: size, height: size });
      }
      return p.resize(SIZE, SIZE, { fit: "cover", position: item.position ?? "centre" });
    };

    const avif = await base().avif({ quality: 60, effort: 6 }).toBuffer();
    const webp = await base().webp({ quality: 72, effort: 6 }).toBuffer();

    for (const [fmt, buf] of [["avif", avif], ["webp", webp]]) {
      if (buf.length >= masterBytes) {
        throw new Error(`[cta] ${item.key}.${fmt} (${buf.length}B) did not shrink below master (${masterBytes}B)`);
      }
      if (buf.length > BUDGET_BYTES) {
        throw new Error(`[cta] ${item.key}.${fmt} is ${buf.length}B, over the ${BUDGET_BYTES}B budget — re-crop or lower quality`);
      }
      await writeFile(path.join(OUT, `${item.key}-${SIZE}.${fmt}`), buf);
    }

    entries[item.key] = {
      alt: item.alt,
      w: SIZE,
      h: SIZE,
      avif: `/cta/${item.key}-${SIZE}.avif`,
      webp: `/cta/${item.key}-${SIZE}.webp`,
    };
    const pct = (1 - Math.min(avif.length, webp.length) / masterBytes) * 100;
    report.push(`  ${item.key.padEnd(10)} ${(masterBytes / 1024).toFixed(0)}KB → avif ${(avif.length / 1024).toFixed(1)}KB / webp ${(webp.length / 1024).toFixed(1)}KB  (−${pct.toFixed(1)}%)`);
  }

  const ts =
    `// AUTO-GENERATED by scripts/cta-images.mjs — do not edit by hand. Run: npm run cta\n` +
    `export type CtaThumb = { alt: string; w: number; h: number; avif: string; webp: string };\n` +
    `export const CTA_THUMBS = ${JSON.stringify(entries, null, 2)} as const satisfies Record<string, CtaThumb>;\n` +
    `export type CtaThumbKey = keyof typeof CTA_THUMBS;\n`;
  await writeFile(MANIFEST_TS, ts);

  console.log("[cta] generated thumbnails:");
  console.log(report.join("\n"));
  console.log(`[cta] wrote ${path.relative(ROOT, MANIFEST_TS)}`);
}

build().catch((err) => {
  console.error(err.message ?? err);
  process.exit(1);
});
