// Typed, validated access to the St. Louis demographic datasets. The committed
// JSON manifests (generated by scripts/generate-demographics.ts) are the only
// runtime source — validated row-by-row through loadCsvManifest, so a bad ingest
// fails loudly instead of rendering wrong numbers on a public campaign page.
//
// Source (cite on every figure): U.S. Census Bureau 2025 Vintage age estimates,
// analysis by J.S. "Ness" Sándoval, Saint Louis University.
import { z } from "zod";
import { loadCsvManifest } from "@/lib/data/csv";
import type { Resource } from "@/lib/data/resource";
import childUnder15 from "./childUnder15ByCounty.json";
import under5Metro from "./under5DeclineByMetro.json";
import stCharles from "./stCharlesAgeStructure.json";
import agingIndex from "./agingIndexByMetro.json";
import msaByAge from "./msaPopulationByAge.json";

export const DEMOGRAPHICS_SOURCE = "U.S. Census Bureau 2025 Vintage · analysis J.S. Sándoval, SLU";

// Require a non-empty numeric cell. Plain z.coerce.number() turns "" → 0
// (Number("") === 0), so a ragged CSV row would ingest silent zeros and render
// fake figures — defeating the fail-loud contract above. We map a blank string to
// NaN before coercion and reject non-finite, so loadCsvManifest fails that row.
// Typed as ZodType<number> (unknown input) so it composes with loadCsvManifest<T>.
const num = z.preprocess(
  (v) => (typeof v === "string" && v.trim() === "" ? NaN : v),
  z.coerce.number().refine(Number.isFinite, "expected a number"),
) as unknown as z.ZodType<number>;

// ── Row schemas (values arrive as strings from the CSV manifest) ──
export const CountyUnder15 = z.object({
  county: z.string().min(1),
  under15_2020: num,
  under15_2025: num,
  change: num,
  pctChange: num,
});
export type CountyUnder15 = z.infer<typeof CountyUnder15>;

export const Under5Metro = z.object({
  metro: z.string().min(1),
  declineUnder5: num,
  pctDecline: num,
});
export type Under5Metro = z.infer<typeof Under5Metro>;

export const AgeStructureRow = z.object({
  ageGroup: z.string().min(1),
  pop2020: num,
  pop2025: num,
  change: num,
});
export type AgeStructureRow = z.infer<typeof AgeStructureRow>;

export const AgingIndexMetro = z.object({
  metro: z.string().min(1),
  agingIndex2020: num,
  agingIndex2025: num,
  agingIndexChange: num,
  agingIndexPctChange: num,
  pct65plus2025: num,
});
export type AgingIndexMetro = z.infer<typeof AgingIndexMetro>;

export const MsaAgeRow = z.object({
  ageGroup: z.string().min(1),
  y2020: num, y2021: num, y2022: num, y2023: num, y2024: num, y2025: num,
  change: num,
});
export type MsaAgeRow = z.infer<typeof MsaAgeRow>;

// ── Loaders (validated Resource<T[]>) ──
export const loadChildUnder15ByCounty = (): Resource<CountyUnder15[]> =>
  loadCsvManifest(childUnder15, CountyUnder15, { source: "Children under 15 by county (2020–2025)" });
export const loadUnder5DeclineByMetro = (): Resource<Under5Metro[]> =>
  loadCsvManifest(under5Metro, Under5Metro, { source: "Children under 5 % decline by metro" });
export const loadStCharlesAgeStructure = (): Resource<AgeStructureRow[]> =>
  loadCsvManifest(stCharles, AgeStructureRow, { source: "St. Charles County age structure (2020 vs 2025)" });
export const loadAgingIndexByMetro = (): Resource<AgingIndexMetro[]> =>
  loadCsvManifest(agingIndex, AgingIndexMetro, { source: "Aging index by metro (2020–2025)" });
export const loadMsaPopulationByAge = (): Resource<MsaAgeRow[]> =>
  loadCsvManifest(msaByAge, MsaAgeRow, { source: "St. Louis MSA population by age (2020–2025)" });

// ── Framing helpers (MO-02 first) ──
// The Missouri counties in the county dataset that make up the MO-02 region.
// (County-level data; the district is a subset of these counties. St. Louis city
// is listed separately in the source and is not in MO-02.)
export const MO02_COUNTY_NAMES = [
  "St. Louis County",
  "St. Charles County",
  "Jefferson County",
  "Franklin County",
  "Warren County",
  "Lincoln County",
] as const;

/** MO-02 county rows, in the fixed order above (ignores IL context + the MSA total). */
export function mo02Counties(rows: CountyUnder15[]): CountyUnder15[] {
  const by = new Map(rows.map((r) => [r.county, r]));
  return MO02_COUNTY_NAMES.map((n) => by.get(n)).filter((r): r is CountyUnder15 => !!r);
}
