import { describe, it, expect, vi, beforeEach } from "vitest";
import sharp from "sharp";

// Orchestration test for promoteToPublicImage: S3 read → web-safe/optimize → S3
// write → asset-meta record. S3 + the metadata store are mocked; the image
// transform (toWebSafeImage) runs for real against tiny sharp-generated bytes.
const getObjectBytes = vi.fn();
const uploadObject = vi.fn();
const putAssetMeta = vi.fn();

vi.mock("@/lib/s3", () => ({
  s3Configured: true,
  getObjectBytes: (k: string) => getObjectBytes(k),
  uploadObject: (...a: unknown[]) => uploadObject(...a),
  publicUrl: (k: string) => `https://cdn.example/${k}`,
}));
vi.mock("@/lib/assets", () => ({ putAssetMeta: (m: unknown) => putAssetMeta(m) }));

import { promoteToPublicImage } from "./promoteMedia";

const png = async () =>
  sharp({ create: { width: 16, height: 16, channels: 3, background: { r: 9, g: 40, b: 90 } } }).png().toBuffer();
const tiff = async () =>
  sharp({ create: { width: 16, height: 16, channels: 3, background: { r: 9, g: 40, b: 90 } } }).tiff().toBuffer();

beforeEach(() => vi.clearAllMocks());

describe("promoteToPublicImage", () => {
  it("rejects a key that isn't in the private/ prefix", async () => {
    await expect(promoteToPublicImage("public/social/x.jpg")).rejects.toThrow(/private/i);
    expect(uploadObject).not.toHaveBeenCalled();
  });

  it("rejects a non-image private object", async () => {
    await expect(promoteToPublicImage("private/docs/plan.pdf")).rejects.toThrow(/image/i);
    expect(uploadObject).not.toHaveBeenCalled();
  });

  it("copies a private photo to a deterministic public/social key and records it", async () => {
    getObjectBytes.mockResolvedValue({ body: await png(), contentType: "image/png" });
    const out = await promoteToPublicImage("private/photos/events/rally.png", "amy@camp.org");

    expect(out.key).toBe("public/social/photos-events-rally.png");
    expect(out.url).toBe("https://cdn.example/public/social/photos-events-rally.png");

    const [key, , contentType] = uploadObject.mock.calls[0];
    expect(key).toBe("public/social/photos-events-rally.png");
    expect(contentType).toBe("image/png");

    const meta = putAssetMeta.mock.calls[0][0];
    expect(meta.visibility).toBe("public");
    expect(meta.tags).toEqual(expect.arrayContaining(["social", "photo"]));
    expect(meta.uploadedBy).toBe("amy@camp.org");
  });

  it("transcodes a HEIC/TIFF master to JPEG and swaps the extension to .jpg", async () => {
    getObjectBytes.mockResolvedValue({ body: await tiff(), contentType: "image/tiff" });
    const out = await promoteToPublicImage("private/photos/candidate/headshot.tiff");

    expect(out.key).toBe("public/social/photos-candidate-headshot.jpg");
    const [key, , contentType] = uploadObject.mock.calls[0];
    expect(key).toBe("public/social/photos-candidate-headshot.jpg");
    expect(contentType).toBe("image/jpeg");
    expect(putAssetMeta.mock.calls[0][0].contentType).toBe("image/jpeg");
  });
});
